# _config.yml is for configuring Jekyll as the SSG.  See https://jekyllrb.com/docs/configuration/ and https://jekyllrb.com/docs/configuration/default/

# Jekyll automatically ignores trying to build HTML out of folders starting w/ an underscore, unless you opt them back in over here.

# Make sure Jekyll doesn't parse files like stackbit.yaml, package.json, or netlify.toml as data sources for HTML rendering
# Default includes:  ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
exclude:
  - stackbit.yaml
  - package.json
  - netlify.toml

#permalink: /:title/index.html # Sadly, no impact on /contact.md's rendering to HTML.  Not with "/:slug/index.html" either.

