# _config.yml is for configuring Jekyll as the SSG.  See https://jekyllrb.com/docs/configuration/ and https://jekyllrb.com/docs/configuration/default/

# Jekyll automatically ignores trying to build HTML out of folders starting w/ an underscore, unless you opt them back in over here.

# Make sure Jekyll doesn't parse files like stackbit.yaml, package.json, or netlify.toml as data sources for HTML rendering
# Default includes:  ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
exclude:
  - README.md
  - stackbit.yaml
  - package.json
  - netlify.toml
  - gatsby-config.js
  - gatsby-node.js
  - old-jekyll-meh-stackbit.yaml
  - old-jekyll-meh-Gemfile
  - old-jekyll-meh-Gemfile.lock
  - old-gatsby-meh-package-lock.json
  - old-gatsby-meh-package.json
  - old-gatsby-meh-stackbit.yaml
  - old-gatsby-meh-stackbit-copy.yaml
  - src/templates
  - src
  - public/
  - dist

#permalink: /:title/index.html # Sadly, no impact on /contact.md's rendering to HTML.  Not with "/:slug/index.html" either.
#defaults: # Also does not work
#  permalink: /:title/index.html # Also does not work

#collections_dir: src/pages/jekyllunderscore
#collections:
#  minnesotatreaties: # The typical way to define a "collection" is to prefix it with an underscore so it's opted out of being built, then opt it back in here.  No need to hand-"include"
#    output: true
#    permalink: /:slug/index.html # This actually works.

defaults:
  - scope:
      path: ""
      type: pages
    values:
      permalink: /annoying-pages/:basename/ # Not sure why this stopped handling `testytest.md` at the root
#  - scope:
#      path: "src/pages/minnesotatreats"
#      type: pages
#    values:
#      permalink: /barsbarsbars/:basename/

overall: katie

hello: world

#contentful:
#  spaces:
#    - singlespace:
#        space:        ENV_CONTENTFUL_SPACE_ID
#        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
#        environment:  ENV_CONTENTFUL_ENVIRONMENT